### ISSUE TITLE
Missing launch files for custom robot cell example

### ISSUE THREAD

**Issue by katallen405** [UniversalRobots/Universal_Robots_ROS2_Documentation#2]
https://docs.universal-robots.com/Universal_Robots_ROS_Documentation/doc/ur_tutorials/my_robot_cell/doc/assemble_urdf.html

This has you create a custom robot cell description and then calls a launch file that does not exist. 
It looks like maybe it expects launch files to be called from somewhere, or a ros package template to be cloned?
Either stepping back to link to creating the ros package and providing the launch file (so that it will build correctly) or linking to a repo that can be cloned would be helpful here.

**Comment by fmauch** [comment]
Adding a link to the respective package (https://github.com/UniversalRobots/Universal_Robots_ROS2_Tutorials/blob/main/my_robot_cell/my_robot_cell_description/) would probably be very beneficial, yes!

Thank you for that hint.

**Comment by fmauch** [comment]
Should be fixed with https://github.com/UniversalRobots/Universal_Robots_ROS2_Tutorials/pull/9

Feel free to comment / reopen if you would like to add something.
